# Capstone 2 - Analyzing Sales with Python

##### Sales Territory 1- Maine 
##### Sales Territory 2- Massachusetts
##### Region- Northeast

In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
customers = pd.read_csv("customer_list.csv")
customers.info()
customers.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 521 entries, 0 to 520
Data columns (total 1 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   cust_id|date|time|name|email|phone|sms-opt-out   521 non-null    object
dtypes: object(1)
memory usage: 4.2+ KB

     cust_id|date|time|name|email|phone|sms-opt-out
0  1|2023-03-15|08:45:12|Rachel|rachel@centralper...
1  2|2023-05-22|12:30:45|R. Geller|rossg@centralp...
2  3|2023-07-09|18:15:27|Monica Geller|chefmonica...
3  4|2023-09-01|21:05:33|Chandler Bing|chandlerb@...
4  5|2023-11-18|14:22:10|Joey|howyoudoing@central...

In [3]:
sales = pd.read_csv("StoreSales.csv")
sales.info()
sales.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 335129 entries, 0 to 335128
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Transaction Date  335129 non-null  object
 1   Store ID          335129 non-null  int64
 2   RewardsID         34943 non-null   float64
 3   Prod Num          335129 non-null  object
 4   Sale Amount       335129 non-null  float64
dtypes: float64(2), int64(1), object(2)
memory usage: 12.8+ MB

  Transaction Date  Store ID  RewardsID  Prod Num  Sale Amount
0         1/1/2022       702        NaN  105349-M         8.00
1         1/1/2022       704        NaN  105350-T       144.00
2         1/1/2022       705        NaN  105351-M        44.00
3         1/1/2022       705        NaN  105352-M        47.61
4         1/1/2022       705        NaN  105353-A        20.36

In [4]:
stored = pd.read_csv("StoreDetail.csv")
stored.info()
stored.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Store Location     111 non-null    object
 1   State              111 non-null    object
 2   Store ID           111 non-null    int64
 3   Territory Manager  111 non-null    object
 4   Region             111 non-null    object
 5   Region Director    111 non-null    object
dtypes: int64(1), object(5)
memory usage: 5.3+ KB

  Store Location     State  Store ID Territory Manager Region  Region Director
0         Aurora  Colorado       701          Jim Heck   West  Cassie Chambers
1       Berthoud  Colorado       702          Jim Heck   West  Cassie Chambers
2        Boulder  Colorado       703          Jim Heck   West  Cassie Chambers
3    Castle Rock  Colorado       704          Jim Heck   West  Cassie Chambers
4         Denver  Colorado       705          Jim Heck   West  Cassie Chambers

In [5]:
products = pd.read_csv("Products.csv")
products.info()
products.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 669 entries, 0 to 668
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Prod Num       669 non-null    object
 1   Product        669 non-null    object
 2   CategoryID     669 non-null    int64
 3   SubcategoryID  669 non-null    object
dtypes: int64(1), object(3)
memory usage: 21.0+ KB

    Prod Num                        Product  CategoryID SubcategoryID
0  105248-IT               TCL NXTPAPER 10s         120       120-tab
1  105249-IT  Dell Latitude 7320 Detachable         120       120-tab
2  105250-IT                     Realme Pad         120       120-tab
3  105251-IT             Lenovo Tab P12 Pro         120       120-tab
4  105252-IT        Microsoft Surface Pro 9         120       120-tab

In [6]:
pcategories = pd.read_csv("ProductCategories.csv")
pcategories.info()
pcategories.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CategoryID     52 non-null     int64
 1   Category       52 non-null     object
 2   SubcategoryID  52 non-null     object
 3   Subcategory    52 non-null     object
dtypes: int64(1), object(3)
memory usage: 1.8+ KB

   CategoryID                  Category SubcategoryID           Subcategory
0         120  Technology & Accessories       120-tab               Tablets
1         120  Technology & Accessories       120-cal           Calculators
2         120  Technology & Accessories       120-sof     Software Download
3         120  Technology & Accessories       120-hea            Headphones
4         120  Technology & Accessories       120-ext  External Accessories

# Core Marking Analysis

In [11]:
# Who are the territory managers for the sales territories assigned? What are the store IDs and cities
# for the stores in each assigned sales territory?
Northeast = stored[(stored['State'] == 'Maine') | (stored['State'] == 'Massachusetts')]  
Northeast
# Territory Manager for Maine is Erbayne Middleton ( Stores 818-823)
# Territory Manager for Massachusetts is Bo Heap ( Stores 730

,Store Location,State,Store ID,Territory Manager,Region,Region Director
37,Bangor,Maine,818,Erbayne Middleton,Northeast,Michael Jarvis
38,Bar Harbor,Maine,819,Erbayne Middleton,Northeast,Michael Jarvis
39,Kennebunkport,Maine,820,Erbayne Middleton,Northeast,Michael Jarvis
40,Lewiston,Maine,821,Erbayne Middleton,Northeast,Michael Jarvis
41,Orono,Maine,822,Erbayne Middleton,Northeast,Michael Jarvis
42,South Portland,Maine,823,Erbayne Middleton,Northeast,Michael Jarvis
52,Boston,Massachusetts,730,Bo Heap,Northeast,Michael Jarvis
53,Attleboro,Massachusetts,801,Bo Heap,Northeast,Michael Jarvis
54,Falmouth,Massachusetts,802,Bo Heap,Northeast,Michael Jarvis
55,Framingham,Massachusetts,803,Bo Heap,Northeast,Michael Jarvis
56,Haverhill,Massachusetts,804,Bo Heap,Northeast,Michael Jarvis
57,Hingham,Massachusetts,805,Bo Heap,Northeast,Michael Jarvis
58,Holyoke,Massachusetts,806,Bo Heap,Northeast,Michael Jarvis
59,Leominster,Massachusetts,807,Bo Heap,Northeast,Michael Jarvis
60,Lowell,Massachusetts,808,Bo Heap,Northeast,Michael Jarvis
61,Lynn,Massachusetts,809,Bo Heap,Northeast,Michael Jarvis
62,Nantucket,Massachusetts,810,Bo Heap,Northeast,Michael Jarvis
63,New Bedford,Massachusetts,811,Bo Heap,Northeast,Michael Jarvis
64,Northampton,Massachusetts,812,Bo Heap,Northeast,Michael Jarvis
65,Pittsfield,Massachusetts,813,Bo Heap,Northeast,Michael Jarvis
66,Provincetown,Massachusetts,814,Bo Heap,Northeast,Michael Jarvis
67,Quincy,Massachusetts,815,Bo Heap,Northeast,Michael Jarvis
68,Somerville,Massachusetts,816,Bo Heap,Northeast,Michael Jarvis
69,Worcester,Massachusetts,817,Bo Heap,Northeast,Michael Jarvis

In [12]:
# What is monthly total revenue for in-store sales in each of the two sales territories, over the full
# period covered by the data?
sales_data = pd.merge(sales,stored, on = "Store ID") 

Northeast = sales_data[
    (sales_data['State'] == 'Maine') |
    (sales_data['State'] == 'Massachusetts')
]

montly_revenue = Northeast.groupby(['State', 'Transaction Date'])['Sale Amount'].sum().reset_index()

montly_revenue

              State Transaction Date  Sale Amount
0             Maine         1/1/2022       124.86
1             Maine         1/1/2023       509.90
2             Maine         1/1/2024      1380.26
3             Maine         1/1/2025       715.38
4             Maine        1/10/2022       234.07
...             ...              ...          ...
2915  Massachusetts         9/8/2025      7752.81
2916  Massachusetts         9/9/2022      2666.77
2917  Massachusetts         9/9/2023      3082.14
2918  Massachusetts         9/9/2024      1988.08
2919  Massachusetts         9/9/2025      5703.08

[2920 rows x 3 columns]

In [13]:
# How would you rank the sales performance of each store in each sales territory? Which are the
# top-performing stores?
stored_ranking =

In [10]:
# Comparing the customer ID from the customer list data with the rewards ID from the sales data,
# who were the top customers in each sales territory?